// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('wphax', ['ngRoute', 'ngAnimate']);

  app.config(function($routeProvider) {
    $routeProvider.when('/', {
      templateUrl: 'home.html',
      resolve: {
        delay: function($q, $timeout) {
          var delay;
          delay = $q.defer();
          $timeout(delay.resolve, 500);
          return delay.promise;
        }
      }
    }).when('/about', {
      templateUrl: 'about.html',
      resolve: {
        delay: function($q, $timeout) {
          var delay;
          delay = $q.defer();
          $timeout(delay.resolve, 500);
          return delay.promise;
        }
      }
    }).when('/work', {
      templateUrl: 'work.html',
      resolve: {
        delay: function($q, $timeout) {
          var delay;
          delay = $q.defer();
          $timeout(delay.resolve, 500);
          return delay.promise;
        }
      }
    }).otherwise('/');
  });

  (function($) {})(jQuery);

}).call(this);
