// Generated by CoffeeScript 1.8.0
(function() {
  var app, resolve;

  app = angular.module('wphax', ['ngRoute', 'ngAnimate']);

  resolve = {
    delay: function($q, $timeout) {
      var delay;
      jQuery('#headings h1, #headings h2, #headings p').toggleClass('ng-enter ng-leave');
      delay = $q.defer();
      $timeout(delay.resolve, 400);
      return delay.promise;
    }
  };

  app.config(function($routeProvider) {
    $routeProvider.when('/', {
      templateUrl: 'home.html',
      resolve: resolve
    }).when('/about', {
      templateUrl: 'about.html',
      resolve: resolve
    }).when('/work', {
      templateUrl: 'work.html',
      resolve: resolve
    }).otherwise('/');
  });

  (function($) {})(jQuery);

}).call(this);
